Feat/remove umd
ice-lab/icestark pull request #254
Opened 2021-02-25 02:27 UTC by maoxiaoke

Closes #240

2021-02-25 03:03 UTC, ClarkXia commented on src/apps.ts
> +  console.log('ccccccc');
无用代码移除

2021-02-25 03:03 UTC, ClarkXia commented on src/apps.ts
> +    lifecycle = getLifecycleFromScript();
lifecycle 不存在的时候的日志是否有输出

2021-02-25 04:14 UTC, maoxiaoke commented on packages/icestark-app/src/setLibraryName.ts
> +  if (library === undefined || library === null) {
如果 library 设置为 0 或 空字符串，我认为是 ok 的

2021-02-26 06:33 UTC, imsobear requested changes

2021-02-26 06:33 UTC, imsobear commented on src/apps.ts
> +  if (appConfig.umd || appConfig.isUmdFetching) {
这个分支加个注释，什么情况下会需要走到这里

2021-02-26 06:33 UTC, imsobear commented on src/apps.ts
> +  if (appConfig.umd || appConfig.isUmdFetching) {
- isUmdFetching 命名优化，比如 loadScriptMode: 'script' | 'fetch'
- 对应的 loadUmdModule 需要改下方法&文件命名，同时实现上也要考虑非 umd 的情况

2021-02-26 06:39 UTC, imsobear commented
剩下的事情：

- icestark@1.x 也需要支持这个能力
- React 脚手架修改：主应用移除 umd={true}
- Vue 脚手架修改：微应用主动引入 setLibrayName、主应用移除 umd={true}

2021-02-26 06:40 UTC, maoxiaoke commented on packages/icestark-app/package.json
> +  "version": "1.3.1",
新 api 递增，是不是次版本号新增更合适些？

2021-03-01 01:51 UTC, imsobear approved these changes

2021-03-01 01:52 UTC, imsobear commented
@ClarkXia 你再简单看一下

2021-03-01 02:49 UTC, ClarkXia commented on src/util/loader.ts
>        if (globalwindow[libraryExport]) {
这块的风险需要看下，不管是不是 umd 都删除最后一个往window 上添加的属性 可能存在问题

2021-03-01 02:49 UTC, ClarkXia commented on tests/loader.umd.spec.ts
> +  const umdSource = fs.readFileSync(path.resolve(__dirname, './umd-not-setlibrary-sample.js'));
非 umd bundle 的测试用例 也需要补充下

2021-03-01 03:03 UTC, maoxiaoke commented on tests/loader.umd.spec.ts
> +  const umdSource = fs.readFileSync(path.resolve(__dirname, './umd-not-setlibrary-sample.js'));
三块测试用例均已添加：
1. js bundle 的测试用例
2. umd 资源，设置了 setLibraryName
3. umd 资源，没有设置 setLibraryName

2021-03-01 03:36 UTC, ClarkXia approved these changes

2021-03-01 03:36 UTC, ClarkXia commented on CHANGELOG.md
> +
`+ ## 2.2.0`

2021-03-01 06:12 UTC, merged