feat/cache css
ice-lab/icestark pull request #374
Opened 2021-08-27 08:13 UTC by maoxiaoke

Closes #373

2021-12-06 12:36 UTC, ClarkXia requested changes

2021-12-06 12:36 UTC, ClarkXia commented on src/apps.ts
> +      : (appSandbox && !appSandbox.sandboxDisabled);
逻辑上可以就判断 loadScriptMode 就行

2021-12-06 12:36 UTC, ClarkXia commented on src/apps.ts
> +            cacheCss: !!((appConfig.loadScriptMode === 'fetch') || appConfig.sandbox || appConfig.umd),
走统一的判读逻辑

2021-12-06 12:36 UTC, ClarkXia commented on src/util/handleAssets.ts
> +      styleElement.id = id;
重复逻辑

2021-12-08 03:16 UTC, maoxiaoke commented on src/apps.ts
> +            cacheCss: !!((appConfig.loadScriptMode === 'fetch') || appConfig.sandbox || appConfig.umd),
done

2021-12-08 03:16 UTC, maoxiaoke commented on src/util/handleAssets.ts
> +      styleElement.id = id;
done

2021-12-09 03:03 UTC, ClarkXia commented on src/AppRouter.tsx
> -    shouldAssetsRemove: () => true,
默认移除，确认下之前的 assets 移除逻辑是否已经兼容

2021-12-09 03:12 UTC, maoxiaoke commented on src/AppRouter.tsx
> -    shouldAssetsRemove: () => true,
是兼容的，有默认的全局设置

2021-12-09 03:20 UTC, ClarkXia approved these changes

2021-12-09 06:26 UTC, merged